### ISSUE TITLE
Adding netrw to sidebars has no effect

### ISSUE THREAD

**Issue by caferen** [projekt0n/github-nvim-theme#239] opened 2023-04-11 04:14 UTC
Below config does not change anything for netrw:

```
require('github-theme').setup({
    theme_style = "dark_default",
    sidebars = { "netrw" },
})
```

If I override `bg_sidebar` then every window's background changes:

```
require('github-theme').setup({
    theme_style = "dark_default",
    sidebars = { "netrw" },
    colors = { bg_sidebar = "#000000" },
})
```

And this one also has no effect at all:

```
require('github-theme').setup({
    theme_style = "dark_default",
    colors = { bg_sidebar = "#000000" },
})
```

**Comment by ful1e5** [comment] 2023-04-11 04:44
@dr4gut Which branch are you using, `main` or `v0.0.x`?

**Comment by dr4gut** [comment] 2023-04-11 04:50
> @dr4gut Which branch are you using, `main` or `v0.0.x`?

@ful1e5 Tried both. Results are the same

**Comment by ful1e5** [comment] 2023-05-03 11:15
The issue has been resolved in 4d5a4ce881d5d412b7f10f6b2fc7b3531a5138cc. Please use the following updated configuration:
```lua
require('github-theme').setup({
  options = {
    darken = {
      sidebars = {
        enable = true,
        list = { 'netrw' },
      },
    },
  },
})

vim.cmd.colorscheme('github_dark')
```

**Closed by ful1e5** 2023-05-03 11:15 UTC

**Comment by caferen** [comment] 2023-05-03 21:58
@ful1e5 so I'm trying this out but I did not get what I expected. Do I maybe understand this feature wrong? I'd expect the netrw window on the left to have a darker background.

![image](https://user-images.githubusercontent.com/60433637/236058943-b634c551-3128-4692-bbb3-dca2ac321b91.png)

I am on master:

![image](https://user-images.githubusercontent.com/60433637/236058887-9cf94ee0-6d9f-429c-84bf-fd78731f5e76.png)

**Comment by ful1e5** [comment] 2023-05-05 10:35
I can't reproduce it. I'm accessing netrw with the `:Explore` command, and it has a dark background. Could you please share your **github-theme** and **netrw** configurations or the steps to reproduce it?

**Comment by dr4gut** [comment] 2023-05-05 23:18
@ful1e5 I clean installed linux and neovim (for other reasons :)) but this problem went away too. Thanks.
