### ISSUE TITLE
Cannot find color shcme 'github_dark'

### ISSUE THREAD

**Issue by MikulasVanousek** [projekt0n/github-nvim-theme#89] opened 2021-09-24 07:10 UTC
I installed this theme with Vim Plug. It appears to be installed...
```
ls ~/.local/share/nvim/plugged/github-nvim-theme/
CHANGELOG.md  colors  extras  LICENSE  lua  Makefile  queries  README.md
```
This is my config to turn it on:
```
" Example config in VimScript
let g:github_function_style = "italic"
let g:github_sidebars = ["qf", "vista_kind", "terminal", "packer"]

" Change the "hint" color to the "orange" color, and make the "error" color bright red
let g:github_colors = [hint = "orange", error = "#ff0000"]

" Load the colorscheme
colorscheme github_dark
```

Yet, when I run wim, the following error appears.

```
Error detected while processing /home/miki/.config/nvim/theme:
line    6:
E121: Undefined variable: hint
line    9:
E185: Cannot find color scheme 'github_dark'
```

**Comment by MikulasVanousek** [comment] 2021-09-24 19:49
I solved ` E185: Cannot find color scheme 'github_dark' ` by removing other theme plugins and running `PlugClean`. If this happens whenever you try to install more than one theme and pick one, it might be useful to mention this in the instructions...

The ` E121: Undefined variable: hint ` persists.

**Comment by ful1e5** [comment] 2021-09-25 03:19
Duplicate of #77

**Closed by ful1e5** 2021-09-25 03:19 UTC
Labels: duplicate

**Comment by ful1e5** [comment] 2021-09-26 09:51
```vim
let g:github_colors = {
  \ 'hint': 'orange',
  \ 'error': '#ff0000'
\ }
```
