### ISSUE TITLE
Cannot use the hl group override feature

### ISSUE THREAD

**Issue by kraftwerk28** [projekt0n/github-nvim-theme#292] opened 2023-08-05 05:58 UTC
`config.lua`:

```lua
require("github-theme").setup({
  groups = {
    all = {
      StatusLine = { link = "Error" },
    },
  },
})

vim.cmd.colorscheme("github_dark_dimmed")
```

Now running neovim with

```bash
$ nvim --noplugin -u config.lua config.lua
```

![image](https://github.com/projekt0n/github-nvim-theme/assets/31807671/350995bf-80e5-4822-815c-970bbfd95dec)

It seems that overrides work fine with `github_dark` and `github_dark_colorblind` colorscheme but are broken with `github_dark_dimmed`, `github_dark_high_contrast`.

**Comment by tmillr** [comment] 2023-08-06 19:51
Seems like I can reproduce this, and it appears to be a bug having to do with the compiler/cache (stale cache, false/incorrect cache hit, etc.) (i.e. if you delete the cache first and then run this it works fine or as expected). This requires debugging and further investigation. Thank you for the bug report.

**Comment by ful1e5** [comment] 2023-09-23 07:14
Closing due to inactivity. Can reopen later.

**Comment by wadefletch** [comment] 2023-11-29 00:42
Was facing a similar issue, and `:GithubThemeCompile` resolved it. Is there a way to automatically run that on config changes? Is that the expected behavior?

**Comment by tmillr** [comment] 2024-06-27 07:57
This appears to be resolved as of the latest HEAD (4f44a5c930372c85483d02700f332d34417e50b2), and should be included in v1.0.2 as well.

**Comment by tmillr** [comment] 2024-07-11 20:11
> Was facing a similar issue (configured styles not being applied), and `:GithubThemeCompile` resolved it. Is there a way to automatically run that on config changes?

@wadefletch Yes, you could always define a `VimEnter` autocmd or something similar, ***but it should be fixed now. Just update your plugin and you should be all good.*** 👍

> Is that the expected behavior?

No, it was due to a bug in the compiler code. The compiler relies on a custom hash function and compiles your config together with theme settings from the plugin to a lua bytecode file. Its purpose is to improve nvim's startup time when loading plugins during startup (which it does).

---

Please open a new issue and/or respond here with a comment if you face any similar issues in the future.

**Closed by tmillr** 2024-07-11 20:11 UTC
